### PR TITLE
Content fixes

### LINKED ISSUE #8: Fix code block styling
The code blocks don't resize on smaller devices

### PR DESCRIPTION
**Pull request by jtomeck**
This pull request will fix:
- code blocks extending past the edge of the screen on mobile.
- resources text on homepage bleeding outside the box on mobile

@kmorel Do you have an opinion on code blocks wrapping vs. not wrapping and having a side-to-side scroll bar on mobile?

closes #8 and #5

### CODE REVIEW

**Comment by kmorel** [comment]
Code blocks should not wrap. You should have to horizontally scroll them instead. Normally I prefer not to have horizontal scrolling, but wrapping lines in code blocks is confusing.

The behavior of the tutorial page (https://deploy-preview-17--vtkm.netlify.app/tutorial) looks good in mobile preview on my desktop Chrome. But when I tried it on my iPhone (both Safari and Chrome), the code blocks wrapped lines. Do you know why that is?

**Comment by jtomeck** [comment]
> But when I tried it on my iPhone (both Safari and Chrome), the code blocks wrapped lines. Do you know why that is?

I'm not sure. I just tried another css rule, that also doesn't seem to work. I'll have to look into this.

**Comment by kmorel** [comment]
https://stackoverflow.com/questions/35469227/overflow-y-not-working-in-safari-inside-a-modal ?

**Comment by jtomeck** [comment]
> https://stackoverflow.com/questions/35469227/overflow-y-not-working-in-safari-inside-a-modal ?

This does not appear to be what's wrong. It's the `whitespace` rules working differently between mobile and desktop. And the fix I just implemented pulls the entire codeblock onto a single line... but the scrolling works.

**Comment by kmorel** [comment]
Did the last commit fix the issue? My iPhone still has issues. I'm not sure if it's because it's still an issue or I can't get the CSS to refresh.

**Comment by jtomeck** [comment]
> Did the last commit fix the issue? My iPhone still has issues. I'm not sure if it's because it's still an issue or I can't get the CSS to refresh.

Sorry I had to run to another meeting before testing. I just tested and it does not appear to have fixed it. I'm very curious what the issue is.

**Comment by jtomeck** [comment]
@kmorel my last commit seems to have fixed the issue. Can you confirm?

**Review by kmorel — APPROVED** [review]

**Comment by kmorel** [comment]
Yes. It seems to be working now.

**Pull request merged**
