### PR TITLE
Assets page

### LINKED ISSUE #18: Both tutorial links should go to the same page
There are two tutorial links on the main page. The first is a tab at the top that takes you to an internal tutorial page. The second is in the link in the resources section.

Why are there two tutorial links? Is there a reason there is a tutorial tab but not, say, a user guide tab?

In any case, the tutorial links should go to the internal version of the tutorial page.

### PR DESCRIPTION
**Pull request by jtomeck**
This PR will:
1. Create dropdown structure for navigation
2. Add resource links from homepage to a resources dropdown in the navigation
3. Remove logos and presentations button from homepage
4. Add "VTK-m Assets" link to the resources section on homepage and dropdown
5. Populate content onto the Assets page

Closes #18 and #10

### CODE REVIEW

**Comment by jtomeck** [comment]
For some reason the markdown inside the table is not getting parsed on build. The screenshot below shows that it works in my local copy, but in the deploy preview it is un-parsed. Looking into that, but I've requested your review anyway @kmorel 

Screen Shot 2021-03-25 at 3 09 13 PM

**Comment by jtomeck** [comment]
Previous commit seems to have fixed the issue. Definitely ready for review now.

**Comment by kmorel** [comment]
Yes, it's working for me now to.

I noticed that the files for the presentations themselves are checked into git. I think those powerpoint files are collectively taking up several 100 MB. Should these be in the git repo itself, or somewhere else? Should they perhaps be in git lfs?

**Comment by jtomeck** [comment]
> Should these be in the git repo itself, or somewhere else? Should they perhaps be in git lfs?

Yeah you are probably right. This is something I am never sure of what the alternatives are. I think it's the plague of being primarily a designer and not knowing what a software engineer would do in these cases. That said, I've never used git lfs, but I can check it out. Thanks for the recommendation!

**Comment by kmorel** [comment]
Another alternative that I often do for web pages hosted by GitHub is to create an associated account on a file sharing site (such as Google Drive). I then upload files there and copy links to the page. It's a little awkward, but it's easy and gives more control on the files and storage. One of the problems with git and git-lfs is that once something is in, it's pretty much in permanently.

**Comment by jtomeck** [comment]
@kmorel - Okay, that sounds like a better solution then. Do you want to be the owner of that folder on Drive? If you want you can share it with me and I can update the links, delete the presentations from the repo and get this merged, pending your approval.

**Comment by kmorel** [comment]
Should I be the "owner" or should someone from Kitware since the page is being hosted from there?

@berkgeveci, what do you think?

**Comment by jtomeck** [comment]
@kmorel - This should be all set now. Sorry for the wait!

**Comment by kmorel** [comment]
Looks good except the image description next to the hero image went missing. We need that there to use the image.

**Comment by jtomeck** [comment]
> Looks good except the image description next to the hero image went missing. We need that there to use the image.

Yeah this branch just didn't have those changes from master. I just pulled those in and will merge now.

**Pull request merged**
